### ISSUE TITLE
[help needed] Couldn't switch to requested monitor resolution when using dxvk

### ISSUE THREAD

**Issue by Yuan-Quan** [VHSgunzo/lutris-wine#10]
when executing `lutris-wine ./GenshinImpact.exe`, with DXVK enabled, got following output:

[pastebin.com/u4YbmWgV](https://pastebin.com/u4YbmWgV)

and got this error
![image](https://user-images.githubusercontent.com/34994002/207555602-768be4b0-a74d-4c99-9f47-897818173c86.png)

Tried a lot of different wine and DXVK version combination, but none worked.

the same issue does not reproduce when I just ues wine-staging 7.22 + DXVK 2.0 ( without lutris-wine)  

This probably is not a lutris-wine issue at all, but I really have no idea.

**Comment by VHSgunzo** [comment]
Hi, why did you turn off D3D EXTRAS? You need to enable this, also try installing the latest Proton GE, but select the DXVK 2.0 version in the settings. Also try to choose wine-22 staging from Kron4ek
![image](https://user-images.githubusercontent.com/57139938/207569536-ee094a60-1e11-47e4-ac58-d271ceabb038.png)

**Comment by VHSgunzo** [comment]
Also try to turn off mangohud and vkbasalt in the lutris-wine settings

**Comment by Yuan-Quan** [comment]
I've already checked the D3D EXTRAS in lutris-wine settings gui, 
and running update all command, it shows d3d_extras v2 DLLs already installed.
But D3D EXTRAS is still disabled.
I tried reset lutris-wine settings, that didn't fix it either

**Comment by VHSgunzo** [comment]
What exactly do you change the settings of lutris-wine? Global or separately for EXE (GenshinImpact.exe) ?
![image](https://user-images.githubusercontent.com/57139938/207624930-4b6b1627-ce4e-45ce-a072-794b8fb53399.png)

**Comment by Yuan-Quan** [comment]
After I changed settings for GenshinImpact.exe, now everything is working fine.  
Thank you for your awesome work, and thank you for your help

**Comment by VHSgunzo** [comment]
Thank you for your feedback ;-)
