### ISSUE TITLE
Some general concerns

### ISSUE THREAD

**Issue by mkrsym1** [VHSgunzo/lutris-wine#15]
I have recently discovered that someone [reuploaded my patch to GitHub](https://github.com/VHSgunzo/sr_patch) and [uploaded a video showcasing the installation process to YouTube](https://www.youtube.com/watch?v=uO6YOuYslRw), both without asking for permission. I think that I've made it clear enough in the readme that you should not do that. After lurking around this repository for a bit, I want to ask the following questions:
1. Why did you not ask me for permission before performing both of the aforementioned actions? You could have, for example, sent me an email or opened an issue on the main patch repository
2. What does this project have to do with [Lutris](https://github.com/lutris/lutris)? It seems completely unrelated, but still has "Lutris" in the name for some reason

**Comment by Mar0xy** [comment]
sir please check https://github.com/VHSgunzo/sr_patch/issues/1 he ignored me

**Comment by mkrsym1** [comment]
Hmm. It seems like @strycore might want to do something about this. Still, I'm waiting for a response to both of my questions.

**Comment by strycore** [comment]
Delete or rename your repository, remove any occurence of the word Lutris.

**Comment by mkrsym1** [comment]
It seems like you have removed the repository where the reuploaded patch was hosted, and instead included it as an archive concatenated to the install script. That does not change the fact that the patch is still reuploaded to GitHub. Also, removing the repository is not even what I asked for, so both questions remain unanswered. Waiting for your response

**Comment by mkrsym1** [comment]
You should also listen to strycore and at least [rename your repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository)

**Comment by VHSgunzo** [comment]
> 1. Why did you not ask me for permission before performing both of the aforementioned actions? You could have, for example, sent me an email or opened an issue on the main patch repository

@mkrsym1
1. What kind of request for use permissions are we talking about, is this written in the README or at least somewhere?
Have you even read the license under which you distribute your patches?
If not, I will remind you that the patches are distributed under the MIT license and here is a small excerpt from it:
```
...
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software
...
```
2. Initially, my project was as an addition to Lutris, adding certain functionality and simplifying work with it, and also Wine runner from Lutris was used by default in my project, and the name itself was taken precisely because of this, and also because the use of other runners other than Wine was not intended, then the project grew up. Now you can still install Wine and some libraries for the prefix from Lutris, but not necessarily.

**Comment by VHSgunzo** [comment]
> Delete or rename your repository, remove any occurence of the word Lutris.

@strycore 
I am not going to rename or delete a project that is already a little more than two years old! (a year of which there is a video on YouTube on launching the game using the patch @mkrsym1) And I don't understand, do you have any personal rights to the word "Lutrsi"? Something I strongly doubt this ...
I hope the Admin from AUR has also clearly explained to you why the package cannot be deleted or renamed.

Although to be honest, I myself have been thinking about renaming the project for a long time, because I'm tired of explaining to people every time that this is not the "inconvenient" lutris, which can't even run the EXE from explorer, because that's what they start telling me at the mention of the word lutris...

**Comment by VHSgunzo** [comment]
> It seems like you have removed the repository where the reuploaded patch was hosted, and instead included it as an archive concatenated to the install script. That does not change the fact that the patch is still reuploaded to GitHub. Also, removing the repository with the reuploaded patch is not even what I asked for, so both questions remain unanswered. Waiting for your response

@mkrsym1
The patch is not in the open and its installation is not possible separately from my project! (only if you really want it and you know what you're doing)
Better look [here](https://github.com/zeroday0619/MyLittleLutrisScripts/raw/master/OBSOLETE%20NO%20MORE%20MAINTAINED/Genshin%20Impact/gi_patch_360.zip)

**Comment by Mar0xy** [comment]
> 1. If not, I will remind you that the patches are distributed under the MIT license and here is a small excerpt from it:

If you would also look at the license.txt file in the patch repo it would say under the following condition:

"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

**Comment by Mar0xy** [comment]
> little more than two years old!

This is not possible as the patches that were made are all less than a year old since we are talking about sr here and not gi

**Comment by VHSgunzo** [comment]
> > 1. If not, I will remind you that the patches are distributed under the MIT license and here is a small excerpt from it:
> 
> If you would also look at the license.txt file in the patch repo it would say under the following condition:
> 
> "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

Yes, but the author of the patch in README forbade any mention of the author and the patches!

**Comment by Mar0xy** [comment]
> any mention of the author and the patches!

and for sr it also forbid the sharing as noted in the very top of the readme 
![image](https://github.com/VHSgunzo/lutris-wine/assets/8841466/99e80584-cc3b-4b39-8450-625366a28844)

**Comment by VHSgunzo** [comment]
> gi

No matter what kind of game we are talking about, the essence does not change from this

**Comment by Mar0xy** [comment]
and sharing also ofc includes any files no matter in which format.

**Comment by Mar0xy** [comment]
> forbade any mention of the author and the patches!

That's why it says "permission notice" as well and not just license but you didn't ask for permission.

**Comment by VHSgunzo** [comment]
And I'm also amused by the fact that for some reason you guys think that the developers of games and anti-cheat do not know that there is an unofficial way to run their games on linux, which also lies in the public domain and Googles in a couple of minutes and has several vedeo on YouTube (not only mine)...

**Comment by mkrsym1** [comment]
> What kind of request for use permissions are we talking about, is this written in the README or at least somewhere?

The readme states that the project should not be shared in public. So, if you intend to share it in public, you should at least ask.

> Have you even read the license under which you distribute your patches?

I am aware that this is not legally enforceable. However, sharing might attract unnecessary attention, so it is in the interests of the users to not share it.

> a year of which there is a video on YouTube on launching the game using the patch

You are thinking of the GI patch, which is not maintained by me. However, that repository has a similar notice about sharing in public.

> The patch is not in the open and its installation is not possible separately from my project!

That does not change the fact that you are sharing it. Is asking really that hard?

> Yes, but the author of the patch in README forbade any mention of the author and the patches!

I did not forbid that specifically, but instead everything that can be considered "sharing in public". You mostly violated that already.

> And I'm also amused by the fact that for some reason you guys think that the developers of games and anti-cheat do not know that there is an unofficial way to run their games on linux, which also lies in the public domain and Googles in a couple of minutes and has several vedeo on YouTube (not only mine)...

Not an excuse for provoking them further. The patches do depend on their good will, but until they've stated officially that this is allowed, we should not assume so.

**Comment by Mar0xy** [comment]
Oh, We know we also keep reminding people that post without permission that they did something wrong and some follow through and delete their videos instead of being stubborn like you.

But just following the rules that are put out still helps out.

**Comment by VHSgunzo** [comment]
OK, what do you want from me now?
I have now renamed the YouTube video (But Youtube's algorithms don't work that easily)

**Comment by VHSgunzo** [comment]
@mkrsym1 
Also, if we have a misunderstanding on the basis of the need to request permission to use, then I want you to add it to the README

**Comment by mkrsym1** [comment]
At least:

1. Clearly state that the patch is not yours (I've seen some people with that misconception under a different video on your channel). I do not request more attribution, however you should still contact and ask the GI patch maintainer
2. Resolve the issue with @strycore . As your project no longer has any relation to Lutris, the name is simply misleading
3. If you are going to do something like this again, please ask for permission. You may receive guidance on what should and should not be done

**Comment by mkrsym1** [comment]
> @mkrsym1 Also, if we have a misunderstanding on the basis of the need to request permission to use, then I want you to add it to the README

I will add it in the future

**Comment by VHSgunzo** [comment]
> 1. Clearly state that the patch is not yours (I've seen some people with that misconception under a different video on your channel). I do not request more attribution, however you should still contact and ask the GI patch maintainer

But I didn't mention anywhere that these were my patches, and I didn't say anywhere that I or anyone else did them, I didn't leave any links, as required in the README. I will even say more, anyone can add a patch to help launch a particular game or application in my project.

By the way, genshin does not need a patch to run now

**Comment by mkrsym1** [comment]
> But I didn't mention anywhere that these were my patches

You did not mention that they are not yours anywhere too. I've seen multiple people with that misconception

> By the way, genshin does not need a patch to run now

And yet you are still distributing it.

**Comment by VHSgunzo** [comment]
> And yet you are still distributing it.

This is done only in case of a sudden change of mind on the part of the developers. 
So far they have not made official statements. because now it's like running a game on steam deck

**Comment by mkrsym1** [comment]
Let me repeat that again. You are distributing it. You have to provide attribution. I'm telling you to ask the maintainer about this. It's not that hard

**Comment by VHSgunzo** [comment]
@strycore 

> I don't think it matters if your project has been using this name for a few years now. If you want for your project to gain any kind of notoriety in the future, I don't see how it could happen while having another project's name.

Perhaps in the future I will create a new project that will include developments from my current project, but the key feature will be a completely redesigned GUI and the project will have a different name unrelated to Lutris, but for now I think everything will remain as it is.


> Then there's the fact that your project distributes stuff that you've been asked not to distribute. I would appreciate if the Lutris branding wasn't associated with that

But Lutris has installers for [gi](https://lutris.net/games/install/37316/view) and [sr](https://lutris.net/games/install/37370/view) that violate the licenses of these games, and as I understand it, they are used when installing games from the Lutris library. But in my project, the use of these patches is optional.

**Comment by Mar0xy** [comment]
> But Lutris has installers for [gi](https://lutris.net/games/install/37316/view) and [sr](https://lutris.net/games/install/37370/view) that violate the licenses of these games, and as I understand it, patches are used when installing games from the Lutris library. But in my project, the use of these patches is optional.

You have completely skipped over this line "Then there's the fact that your project distributes stuff that you've been asked not to distribute. " while the patches for both game were distributed with permission as the launchers don't directly link to it.

> But in my project, the use of these patches is optional.

Yea, sure try running SR without it

**Comment by VHSgunzo** [comment]
> You have completely skipped over this line "Then there's the fact that your project distributes stuff that you've been asked not to distribute. "
> 
> while the patches for both games were distributed with permission as the sr launcher doesn't directly link to it or share it and for gi the person came to the patch maintainer and asked.

I said this because @strycore cares about the branding of lutris in terms of the fact that there is the word lutris in the name of my project and I did not ask permission to use patches that initially violate the license of these games, although the same thing happens in lutris itself, and the patch for genshin in lutris is generally distributed completely in open form, no matter who there what and from whom I asked

> Yea, sure try running SR without it

This is another question, in the Lutris installer, both patches violating the license of these games are enforced

**Comment by cybik** [comment]
> Lol, what? What exactly are the "Nvidia drivers" that I "distribute"?

Quite literally all of it:
https://github.com/VHSgunzo/runimage-nvidia-drivers/releases/tag/v530.41.03

**Comment by VHSgunzo** [comment]
> > Lol, what? What exactly are the "Nvidia drivers" that I "distribute"?
> 
> Quite literally all of it: https://github.com/VHSgunzo/runimage-nvidia-drivers/releases/tag/v530.41.03

These are not "nvidia drivers", as such, and if you don't understand what it is, then it's better not to climb

**Comment by VHSgunzo** [comment]
@cybik 
Nvidia LICENSE:
```
...
2.1.2  Linux/FreeBSD Exception.  Notwithstanding the foregoing terms
of Section 2.1.1, SOFTWARE designed exclusively for use on the Linux or
FreeBSD operating systems, or other operating systems derived from the
source code to these operating systems, may be copied and redistributed,
provided that the binary files thereof are not modified in any way
(except for unzipping of compressed files).
...
```

**Comment by cybik** [comment]
> @cybik Nvidia LICENSE:
> 
> ```
> ...
> 2.1.2  Linux/FreeBSD Exception.  Notwithstanding the foregoing terms
> of Section 2.1.1, SOFTWARE designed exclusively for use on the Linux or
> FreeBSD operating systems, or other operating systems derived from the
> source code to these operating systems, may be copied and redistributed,
> provided that the binary files thereof are not modified in any way
> (except for unzipping of compressed files).
> ...
> ```

You remove libraries. You are altering the software package itself. And thus:

```        2.1.3 Limitations.

            No Reverse Engineering. Customer may not reverse engineer, decompile, or disassemble the SOFTWARE, nor attempt in any other manner to obtain the source code.

            No Separation of Components. The SOFTWARE is licensed as a single product. Its component parts may not be separated for use on more than one computer, nor otherwise used separately from the other parts.
```
You violate section `2.1.3 Limitations` of the driver license available at https://www.nvidia.com/en-us/drivers/nvidia-license/.

**Comment by cybik** [comment]
Package managers in standard Debian, Ubuntu, Pop, Redhat/Fedora, Suse and all derivatives, also have ***multiple*** packages and a system designed so that the integrity of the original nVidia driver installer runtime's software package is preserved (unless the user manually says to not install one component or another - which is, at that point, up to the user themselves and not the redistributor, clearing the redistributor's responsibility).

If you had multiple squashfs images containing all the things your packaging script removed, you COULD argue you're doing this. Here, you obviously don't - you remove a bunch of stuff, including the documentation, and you don't redistribute it anywhere else, thus violating section 2.1.3 as stated above.

Which brings us to this:
```
3. TERMINATION

    This LICENSE will automatically terminate if Customer fails to comply with any of the terms and conditions hereof. In such event, Customer must destroy all copies of the SOFTWARE and all of its component parts.
```

As you are in direct violation of 2.1.3 [per what your script does](https://github.com/VHSgunzo/runimage-nvidia-drivers/blob/main/create_nvidia_driver_image#L51-L53), the license would compel you to stop what you're doing and delete the package you're building and distributing, at least.

**Comment by VHSgunzo** [comment]
> If you had multiple squashfs images containing all the things your packaging script removed

This container module is loaded or assembled only on 
linux computers of Nvidia users, and they already have all the deleted items from the container module

**Comment by cybik** [comment]
> > If you had multiple squashfs images containing all the things your packaging script removed
> 
> This container module is loaded or assembled only on linux computers of Nvidia users, and they already have all the deleted items from the container module

That is **_completely irrelevant_**. You can't assume the presence of any other components. Either you redistribute it in whole, or you don't redistribute it at all.

**Comment by Mar0xy** [comment]
Just no one really wants to bother with you anymore cause you just don't listen and it's pointless fighting with you at that point.

Instead at this point it's better to escalate this than to keep fighting with you on a personal level.

**Comment by Mar0xy** [comment]
> Said those who themselves violate the license for a bunch of anime games...

Said the guy who is doing the same thing...

**Comment by VHSgunzo** [comment]
> Said the guy who is doing the same thing...

Well, at least I'm not saying that I will "escalate" the situation and not inflate the tragedy out of nothing here... If you really would like no one to know about the patch, then you didn't need to put it in open access, you didn't need to make instructions for use, separate launchers and other things that you did yourself, and now you're whining that someone uses it and distributes ...

Honestly speaking of which, I don't really care about these anime games, I don't play them and added patches because I was asked to do it

If you don't like what I'm doing, then don't use it! I don't force anyone to use it, I don't sell my projects to anyone and I don't take money for it, even in the form of donations!

**Comment by Mar0xy** [comment]
> added patches because I was asked to do it

Yea but you got linked to them which was already breaking the do not share part, then proceeded to make a repo to share it without asking the maintainer and again breaking the do not share part.

> If you really would like no one to know about the patch, then you didn't need to put it in open access, you didn't need to make instructions for use, separate launchers and other things that you did yourself

The reason the patch is out there for the public to use is cause it was meant for that reason the reason we say why **YOU** should not share it is to prevent the damage to minimal costs everywhere else where you can find the patch either has an agreement with the patch maintainer.

the "but then the launchers and etc shouldn't exist" thing doesn't apply here and is irrelevant as they are simply meant to make it easier for users to use the stuff without leaking information out as we never link to the stuff or share the files right away unlike **YOU**

The videos that exist all also were made with permission as long as they followed our guidelines like:
1. not mentioning the game by name
2. not sharing the links or files in description or comments

These guidelines are all also followed by the launchers in the repos as well.

**Comment by VHSgunzo** [comment]
> The reason the patch is out there for the public to use is cause it was meant for that reason

Well, again, you contradict yourself... What constructive dialogue can go on with you?

**Comment by VHSgunzo** [comment]
> Just admit that you're using the word lutris to masquerade as some sort of trustable Lutris addon or something, and possibly for SEO. You're the biggest cloutchaser I've seen on GitHub dot com period

Are you a bastard? I suggest you reread everything here from the beginning, if you are so stupid. And shove your comments up your ass the way you like to do it.
