### ISSUE TITLE
How  to setup Game in Lutris Launcher?

### ISSUE THREAD

**Issue by cindrmon** [VHSgunzo/lutris-wine#3]
When I run `lutris-wine -addtolu <Game Executable>`, the script seems to add the game on Lutris, but it doesn't seem to use the appropriate wine version, which uses the default `lutris-7.2.2` by default. How do I set it up properly on Lutris?

**Comment by VHSgunzo** [comment]
My project is not a fork of Lutris, but a separately developed utility with more advanced functionality. If you want to use Lutris, then you need to configure the game added to Lutris in Lutris itself.

**Comment by cindrmon** [comment]
understandable. thank you for the clarification
