### ISSUE TITLE
How to setup 

### ISSUE THREAD

**Issue by adilhyz** [VHSgunzo/lutris-wine#7]
how to run lutris-wine on debian base

**Comment by niizam** [comment]
1. Add i386 architecture
`sudo dpkg --add-architecture i386 `
`sudo apt update`

2. Install the dependencies

`sudo apt install libasound2-dev
libasound2-plugins libasound2:i386 libasound2-plugins:i386
aria2
bc
cabextract
coreutils
curl
desktop-file-utils
libfuse2
gamemode gamemode-dev
giflib-tools libgif-dev libgif7
libglu1-mesa libglu1-mesa-dev libglu1-mesa:i386 libglu1-mesa-dev:i386
gnutls-bin libgnutls28-dev libgnutls30 guile-gnutls
libgtk-3-bin libgtk-3-dev libgtk-3-common libgail-3-dev
icoutils
imagemagick
iputils-clockdiff iputils-ping iputils-tracepath
libgcrypt20 libgcrypt20:i386
libgpg-error0 libgpg-error-dev
libjpeg-turbo8:i386 libjpeg-turbo8-dev:i386 libjpeg-turbo8 libjpeg-turbo8-dev
libldap-dev:i386 libldap-dev
libpng-dev libpng-dev:i386
libpulse-dev libpulse-mainloop-glib0 libpulse-dev:i386 libpulse-mainloop-glib0:i386 pulseaudio-utils
libva-dev libva2 libva2:i386 libva-dev:i386
mesa-va-drivers mesa-va-drivers:i386
libxcomposite1 libxcomposite-dev libxcomposite1:i386 libxcomposite-dev:i386
libxinerama-dev libxinerama1 libxinerama-dev:i386 libxinerama1:i386
libxslt1-dev libxslt1.1 libxslt1-dev:i386 libxslt1.1:i386
mangohud
libosmesa6-dev libglx-mesa0 libegl-mesa0 libgbm-dev libgbm1 libglapi-mesa libxatracker-dev libxatracker2 libd3dadapter9-mesa libgl1-mesa-dri libosmesa6-dev:i386 libglx-mesa0:i386 libegl-mesa0:i386 libgbm-dev:i386 libgbm1:i386 libglapi-mesa:i386
libxatracker-dev:i386 libxatracker2:i386 libd3dadapter9-mesa:i386 libgl1-mesa-dri:i386
mesa-utils mesa-vdpau-drivers
libmpg123-dev libmpg123-0 libmpg123-dev:i386 libmpg123-0:i386
libncurses-dev lib32ncurses-dev
libopenal-dev libopenal1 libopenal-dev:i386 libopenal1:i386
ocl-icd-libopencl1 ocl-icd-opencl-dev ocl-icd-libopencl1:i386 ocl-icd-opencl-dev:i386
libsqlite3-0 libsqlite3-dev libsqlite3-0:i386 libsqlite3-dev:i386
libv4l-dev libv4l-0 libv4l-dev:i386 libv4l-0:i386
vkbasalt
libvulkan-dev libvulkan1 libvulkan-dev:i386 libvulkan1:i386
mesa-vulkan-drivers mesa-vulkan-drivers:i386
openssl
perl
qttools5-dev libqt5designer5
squashfs-tools
squashfuse
unzip
vulkan-tools
xdelta3
xdg-utils
xfonts-100dpi
xfonts-75dpi
xfonts-cyrillic
x11-xserver-utils x11-utils
xterm
yad
zenity
vkbasalt
libarchive-tools`

3. Compile manually these libraries (optional but necessary)
`https://github.com/ishitatsuyuki/LatencyFleX`
`https://gitlab.com/torkel104/libstrangle`

4. Install lutris-wine
`sudo su`
`curl -fsSL "https://github.com/VHSgunzo/lutris-wine/releases/download/v0.75.4/lutris-wine-git-0.75.4.r0.g5510d3e-1-x86_64.pkg.tar.zst"  | bsdtar -C / -xvf -`

**Comment by VHSgunzo** [comment]
@adilhyz 
Hi, I'm making a special portable [container](https://github.com/VHSgunzo/runimage) with all the necessary dependencies, which helps to run my project on almost any linux x86_64 distribution.
Tests were also carried out on Debian based distributions

Check [README](https://github.com/VHSgunzo/lutris-wine#installation)
